# Movie Recommendation System

A personal project focused on recommending movie titles based on the cosine similarity among movies in the given IMDB dataset. I have followed the article: https://towardsdatascience.com/how-to-build-from-scratch-a-content-based-movie-recommender-with-natural-language-processing-25ad400eb243
However, my approach differs in data cleaning, data preprocessing and feature selection.


In [1]:
#import libraries

import numpy as np
import pandas as pd
import nltk

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity


In [2]:
#loading the IMDB Dataset

df = pd.read_csv('https://query.data.world/s/uikepcpffyo2nhig52xxeevdialfl7')

#exploring what the data looks like 
df.head()



Unnamed: 0                     Title  Year     Rated     Released  Runtime  \
0           1  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1           2             The Godfather  1972         R  24 Mar 1972  175 min   
2           3    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           4           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4           5              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  ... tomatoConsensus  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...  ...             NaN   
1  Marlon Brando, Al Pacino, James Caan, Richard ...  ...             NaN   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...  ...             NaN   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...  ...             NaN   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....  ...             NaN   

  tomatoUserMeter tomatoUserRating tomatoUserReviews  \
0             NaN              NaN               NaN   
1             NaN              NaN               NaN   
2             NaN              NaN               NaN   
3             NaN              NaN               NaN   
4             NaN              NaN               NaN   

                                           tomatoURL          DVD  \
0  http://www.rottentomatoes.com/m/shawshank_rede...  27 Jan 1998   
1         http://www.rottentomatoes.com/m/godfather/  09 Oct 2001   
2  http://www.rottentomatoes.com/m/godfather_part...  24 May 2005   
3   http://www.rottentomatoes.com/m/the_dark_knight/  09 Dec 2008   
4  http://www.rottentomatoes.com/m/1000013-12_ang...  06 Mar 2001   

      BoxOffice                       Production  \
0           NaN                Columbia Pictures   
1           NaN               Paramount Pictures   
2           NaN               Paramount Pictures   
3  $533,316,061  Warner Bros. Pictures/Legendary   
4           NaN             Criterion Collection   

                                             Website Response  
0                                                NaN     True  
1                        http://www.thegodfather.com     True  
2                       http://www.thegodfather.com/     True  
3               http://thedarkknight.warnerbros.com/     True  
4  http://www.criterion.com/films/27871-12-angry-men     True  

[5 rows x 38 columns]

## Data Preprocessing and Cleaning

In [3]:
#removing unnamed columns
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df.head()


Title  Year     Rated     Released  Runtime  \
0  The Shawshank Redemption  1994         R  14 Oct 1994  142 min   
1             The Godfather  1972         R  24 Mar 1972  175 min   
2    The Godfather: Part II  1974         R  20 Dec 1974  202 min   
3           The Dark Knight  2008     PG-13  18 Jul 2008  152 min   
4              12 Angry Men  1957  APPROVED  01 Apr 1957   96 min   

                  Genre              Director  \
0          Crime, Drama        Frank Darabont   
1          Crime, Drama  Francis Ford Coppola   
2          Crime, Drama  Francis Ford Coppola   
3  Action, Crime, Drama     Christopher Nolan   
4          Crime, Drama          Sidney Lumet   

                                              Writer  \
0  Stephen King (short story "Rita Hayworth and S...   
1  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola (screenplay), Mario Puzo ...   
3  Jonathan Nolan (screenplay), Christopher Nolan...   
4  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot  ... tomatoConsensus  \
0  Two imprisoned men bond over a number of years...  ...             NaN   
1  The aging patriarch of an organized crime dyna...  ...             NaN   
2  The early life and career of Vito Corleone in ...  ...             NaN   
3  When the menace known as the Joker emerges fro...  ...             NaN   
4  A jury holdout attempts to prevent a miscarria...  ...             NaN   

  tomatoUserMeter tomatoUserRating tomatoUserReviews  \
0             NaN              NaN               NaN   
1             NaN              NaN               NaN   
2             NaN              NaN               NaN   
3             NaN              NaN               NaN   
4             NaN              NaN               NaN   

                                           tomatoURL          DVD  \
0  http://www.rottentomatoes.com/m/shawshank_rede...  27 Jan 1998   
1         http://www.rottentomatoes.com/m/godfather/  09 Oct 2001   
2  http://www.rottentomatoes.com/m/godfather_part...  24 May 2005   
3   http://www.rottentomatoes.com/m/the_dark_knight/  09 Dec 2008   
4  http://www.rottentomatoes.com/m/1000013-12_ang...  06 Mar 2001   

      BoxOffice                       Production  \
0           NaN                Columbia Pictures   
1           NaN               Paramount Pictures   
2           NaN               Paramount Pictures   
3  $533,316,061  Warner Bros. Pictures/Legendary   
4           NaN             Criterion Collection   

                                             Website Response  
0                                                NaN     True  
1                        http://www.thegodfather.com     True  
2                       http://www.thegodfather.com/     True  
3               http://thedarkknight.warnerbros.com/     True  
4  http://www.criterion.com/films/27871-12-angry-men     True  

[5 rows x 37 columns]

In [4]:
# A lot of the columns are irrelevant for movie recommendations and can be removed

df = df[['Title','Year','Rated','Runtime',
         'Genre','Director','Writer','Actors',
         'Plot','Production']]
df.head()


Title  Year     Rated  Runtime                 Genre  \
0  The Shawshank Redemption  1994         R  142 min          Crime, Drama   
1             The Godfather  1972         R  175 min          Crime, Drama   
2    The Godfather: Part II  1974         R  202 min          Crime, Drama   
3           The Dark Knight  2008     PG-13  152 min  Action, Crime, Drama   
4              12 Angry Men  1957  APPROVED   96 min          Crime, Drama   

               Director                                             Writer  \
0        Frank Darabont  Stephen King (short story "Rita Hayworth and S...   
1  Francis Ford Coppola  Mario Puzo (screenplay), Francis Ford Coppola ...   
2  Francis Ford Coppola  Francis Ford Coppola (screenplay), Mario Puzo ...   
3     Christopher Nolan  Jonathan Nolan (screenplay), Christopher Nolan...   
4          Sidney Lumet  Reginald Rose (story), Reginald Rose (screenplay)   

                                              Actors  \
0  Tim Robbins, Morgan Freeman, Bob Gunton, Willi...   
1  Marlon Brando, Al Pacino, James Caan, Richard ...   
2  Al Pacino, Robert Duvall, Diane Keaton, Robert...   
3  Christian Bale, Heath Ledger, Aaron Eckhart, M...   
4  Martin Balsam, John Fiedler, Lee J. Cobb, E.G....   

                                                Plot  \
0  Two imprisoned men bond over a number of years...   
1  The aging patriarch of an organized crime dyna...   
2  The early life and career of Vito Corleone in ...   
3  When the menace known as the Joker emerges fro...   
4  A jury holdout attempts to prevent a miscarria...   

                        Production  
0                Columbia Pictures  
1               Paramount Pictures  
2               Paramount Pictures  
3  Warner Bros. Pictures/Legendary  
4             Criterion Collection

In [5]:
'''Checking if the dataframe has any rows 
with null values and then removing those 
rows from the dataframe
'''
print(df.isnull().sum())
df = df.dropna(how='any',axis=0)
print("After removing the null values")
print(df.isnull().sum())

Title         0
Year          0
Rated         0
Runtime       0
Genre         0
Director      0
Writer        1
Actors        0
Plot          0
Production    0
dtype: int64
After removing the null values
Title         0
Year          0
Rated         0
Runtime       0
Genre         0
Director      0
Writer        0
Actors        0
Plot          0
Production    0
dtype: int64


In [6]:
#Converting all columns except the title to lowercase 
title = df['Title']
df = df.applymap(lambda s:s.lower() if type(s) == str else s)
df['Title']=title
df.head()


Title  Year     Rated  Runtime                 Genre  \
0  The Shawshank Redemption  1994         r  142 min          crime, drama   
1             The Godfather  1972         r  175 min          crime, drama   
2    The Godfather: Part II  1974         r  202 min          crime, drama   
3           The Dark Knight  2008     pg-13  152 min  action, crime, drama   
4              12 Angry Men  1957  approved   96 min          crime, drama   

               Director                                             Writer  \
0        frank darabont  stephen king (short story "rita hayworth and s...   
1  francis ford coppola  mario puzo (screenplay), francis ford coppola ...   
2  francis ford coppola  francis ford coppola (screenplay), mario puzo ...   
3     christopher nolan  jonathan nolan (screenplay), christopher nolan...   
4          sidney lumet  reginald rose (story), reginald rose (screenplay)   

                                              Actors  \
0  tim robbins, morgan freeman, bob gunton, willi...   
1  marlon brando, al pacino, james caan, richard ...   
2  al pacino, robert duvall, diane keaton, robert...   
3  christian bale, heath ledger, aaron eckhart, m...   
4  martin balsam, john fiedler, lee j. cobb, e.g....   

                                                Plot  \
0  two imprisoned men bond over a number of years...   
1  the aging patriarch of an organized crime dyna...   
2  the early life and career of vito corleone in ...   
3  when the menace known as the joker emerges fro...   
4  a jury holdout attempts to prevent a miscarria...   

                        Production  
0                columbia pictures  
1               paramount pictures  
2               paramount pictures  
3  warner bros. pictures/legendary  
4             criterion collection

In [8]:
#Converting all features into keywords that will be used to calculate cosine similarity later on 

#Genre
#replacing comma with a space 
df['Genre']=df['Genre'].apply(lambda x: str(x.replace(',',' ')))

#Director
#Combining the first and last names together 
df['Director']=df['Director'].apply(lambda x: str(x.replace(' ','')))

#Production
#Combining the name into one 
df['Production']=df['Production'].apply(lambda x: str(x.replace(' ','')))
df['Production']=df['Production'].apply(lambda x: str(x.replace('.','')))

#Actors 
#Selecting the first two(lead) actors
df['Actors']=df['Actors'].apply(lambda x: str(x.replace(' ','')))
df['Actors'] = df['Actors'].map(lambda x: x.split(',')[:2])

#Writer
df['Writer'] = df['Writer'].apply(lambda x: str(x.replace(' ','')))
df['Writer'] = df['Writer'].map(lambda x: x.split('(')[:1])

#Runtime 
df['Runtime'] = df['Runtime'].map(lambda x: x.split(' ')[:1])

#Plot 
#Remove punctuations, stop words
stop_words = set(stopwords.words('english'))
porter = PorterStemmer()
df['Plot'] = df['Plot'].apply(lambda x: ' '.join(
    [word for word in x.split() if word not in 
    (stop_words)]))
df['Plot'] = df['Plot'].str.replace('[^\w\s]','')




In [9]:
df.head()

Title  Year     Rated Runtime                 Genre  \
0  The Shawshank Redemption  1994         r   [142]          crime  drama   
1             The Godfather  1972         r   [175]          crime  drama   
2    The Godfather: Part II  1974         r   [202]          crime  drama   
3           The Dark Knight  2008     pg-13   [152]  action  crime  drama   
4              12 Angry Men  1957  approved    [96]          crime  drama   

             Director                Writer                        Actors  \
0       frankdarabont         [stephenking]   [timrobbins, morganfreeman]   
1  francisfordcoppola           [mariopuzo]      [marlonbrando, alpacino]   
2  francisfordcoppola  [francisfordcoppola]      [alpacino, robertduvall]   
3    christophernolan       [jonathannolan]  [christianbale, heathledger]   
4         sidneylumet        [reginaldrose]   [martinbalsam, johnfiedler]   

                                                Plot  \
0  two imprisoned men bond number years finding s...   
1  aging patriarch organized crime dynasty transf...   
2  early life career vito corleone 1920s new york...   
3  menace known joker emerges mysterious past wre...   
4  jury holdout attempts prevent miscarriage just...   

                     Production  
0              columbiapictures  
1             paramountpictures  
2             paramountpictures  
3  warnerbrospictures/legendary  
4           criterioncollection

In [10]:
#merging all the keywords together into one 

data = pd.DataFrame()

data['Keywords'] = df[df.columns[1:]].apply(
    lambda x: ' '.join(x.dropna().astype(str)),
    axis=1
)
data['Title'] = df['Title']
data.set_index('Title',inplace=True)
data['Keywords']=data['Keywords'].str.replace('[','')
data['Keywords']=data['Keywords'].str.replace(']','') 
data['Keywords']=data['Keywords'].str.replace("'","") 

data.head()

Keywords
Title                                                                      
The Shawshank Redemption  1994 r 142 crime  drama frankdarabont stephenk...
The Godfather             1972 r 175 crime  drama francisfordcoppola mar...
The Godfather: Part II    1974 r 202 crime  drama francisfordcoppola fra...
The Dark Knight           2008 pg-13 152 action  crime  drama christophe...
12 Angry Men              1957 approved 96 crime  drama sidneylumet regi...

## Recommendation System

In [11]:
#Cosine similarity
count_vector_matrix = CountVectorizer().fit_transform(data['Keywords'])
cos_similarity = cosine_similarity(count_vector_matrix,count_vector_matrix)
print('Cosine Similarity Matrix')
print(cos_similarity)

Cosine Similarity Matrix
[[1.         0.13636364 0.11677484 ... 0.09090909 0.04652421 0.04652421]
 [0.13636364 1.         0.38924947 ... 0.04545455 0.04652421 0.04652421]
 [0.11677484 0.38924947 1.         ... 0.03892495 0.03984095 0.03984095]
 ...
 [0.09090909 0.04545455 0.03892495 ... 1.         0.04652421 0.04652421]
 [0.04652421 0.04652421 0.03984095 ... 0.04652421 1.         0.04761905]
 [0.04652421 0.04652421 0.03984095 ... 0.04652421 0.04761905 1.        ]]


In [12]:
#returns the n(input) most similar movies to the title(input) based on cosine_similarity
def recommend_similar(title,n):
    #selecting the row of the movie title 
    rows = pd.Series(data.index)
    row = rows[rows==title]
    row = row.index[0]
    similar_movies = pd.Series(cos_similarity[row])
    similar_movies = similar_movies.sort_values(ascending=False)
    top_three_movies = similar_movies.iloc[1:n+1]
    top_three_movies = list(top_three_movies.index)
    movie_titles = []
    for movie in top_three_movies:
        movie_titles.append(list(data.index)[movie])
    return movie_titles
    
    

In [13]:
#testing the recommendation function
print(recommend_similar('The Shawshank Redemption',4))
print(recommend_similar('The Dark Knight',2))

['Pulp Fiction', 'Rope', 'Goodfellas', 'Se7en']
['The Dark Knight Rises', 'Batman Begins']
